# Generated by Django 3.2 on 2022-06-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('identity', models.CharField(choices=[('landlord', '房東'), ('resident', '住戶'), ('non-resident', '非住戶')], max_length=20)),
            ],
        ),
    ]
