# Generated by Django 3.2 on 2022-06-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0007_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='roomnumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpsite.room'),
        ),
    ]
