# Generated by Django 3.2 on 2022-06-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0009_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='roomnumber',
            field=models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='fpsite.room'),
        ),
    ]
