# Generated by Django 3.2 on 2022-06-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0010_tenant_roomnumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tenant',
            new_name='Resident',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
    ]
