# Generated by Django 3.2 on 2022-06-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0011_auto_20220611_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='date_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='date_start',
            field=models.DateField(blank=True),
        ),
    ]
