# Generated by Django 3.2 on 2022-06-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0012_auto_20220611_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='message',
            field=models.TextField(default='無'),
        ),
    ]
