# Generated by Django 3.2 on 2022-06-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0018_alter_account_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
