# Generated by Django 3.2 on 2022-06-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0022_alter_account_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('identity', models.CharField(choices=[('resident', '住戶'), ('non-resident', '非住戶'), ('landlord', '房東')], default='住戶', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
