# Generated by Django 3.2 on 2022-06-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0023_auto_20220611_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
