# Generated by Django 3.2 on 2022-06-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0025_auto_20220612_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default='example@example.com', max_length=20),
            preserve_default=False,
        ),
    ]
