# Generated by Django 3.2 on 2022-06-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0028_alter_resident_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rent',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
