# Generated by Django 3.2 on 2022-06-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0029_alter_room_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rent',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
