# Generated by Django 3.2 on 2022-06-12 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0031_alter_room_rent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_bill', models.PositiveIntegerField()),
                ('current_bill', models.PositiveIntegerField()),
                ('roomnumber', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='fpsite.room')),
            ],
        ),
    ]
