# Generated by Django 3.2 on 2022-06-13 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0032_electricity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electricity_total',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('totaluse', models.PositiveIntegerField()),
                ('totalbill', models.PositiveIntegerField()),
                ('per_price', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Electricity_personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_use', models.DecimalField(decimal_places=1, max_digits=10)),
                ('current_use', models.DecimalField(decimal_places=1, max_digits=10)),
                ('avg_totaluse', models.DecimalField(decimal_places=1, max_digits=10)),
                ('personaluse', models.DecimalField(decimal_places=1, max_digits=10)),
                ('bill', models.DecimalField(decimal_places=0, max_digits=10)),
                ('roomnumber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fpsite.room')),
            ],
        ),
    ]
