# Generated by Django 3.2 on 2022-06-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0034_auto_20220613_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricity_personal',
            name='avg_totaluse',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='electricity_personal',
            name='bill',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='electricity_personal',
            name='current_use',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='electricity_personal',
            name='last_use',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='electricity_personal',
            name='personaluse',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
