# Generated by Django 3.2 on 2022-06-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0035_auto_20220613_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricity_total',
            name='current',
            field=models.CharField(default='current', max_length=10),
        ),
    ]
