# Generated by Django 3.2 on 2022-06-13 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0036_electricity_total_current'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Electricity',
        ),
    ]
