# Generated by Django 3.2 on 2022-06-14 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fpsite', '0037_delete_electricity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='roomnumber',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='fpsite.room'),
        ),
    ]
